# Generated by Django 4.0.1 on 2022-03-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testType', models.CharField(max_length=30, null=True)),
                ('testResult', models.TextField(null=True)),
            ],
            options={
                'db_table': 'labtest',
            },
        ),
    ]
