# Generated by Django 4.0.1 on 2022-03-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
        ('hospital_staffs', '0003_hospitalstaffprofile_address_and_more'),
        ('lab_staffs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labstaffprofile',
            name='patientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='labstaffprofile',
            name='staffId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_staffs.hospitalstaffprofile'),
        ),
        migrations.AddField(
            model_name='labstaffprofile',
            name='testResult',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='labstaffprofile',
            name='testType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='labstaffprofile',
            table='labtest',
        ),
    ]
