# Generated by Django 4.0.1 on 2022-03-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_staffs', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labstaffprofile',
            name='user',
        ),
    ]
