# Generated by Django 4.0.1 on 2022-03-16 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_staffs', '0002_initial'),
        ('patients', '0002_initial'),
        ('lab_staffs', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labstaffprofile',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='labstaffprofile',
            name='testResult',
        ),
        migrations.RemoveField(
            model_name='labstaffprofile',
            name='testType',
        ),
        migrations.AlterModelTable(
            name='labstaffprofile',
            table=None,
        ),
        migrations.CreateModel(
            name='LabTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testType', models.CharField(max_length=30, null=True)),
                ('testResult', models.TextField(null=True)),
                ('patientId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
                ('staffId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_staffs.hospitalstaffprofile')),
            ],
            options={
                'db_table': 'labtest',
            },
        ),
    ]
