# Generated by Django 4.0.1 on 2022-03-18 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patientrecords_unique_together'),
        ('hospital_staffs', '0002_initial'),
        ('lab_staffs', '0004_remove_labstaffprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labstaffprofile',
            name='patientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='labstaffprofile',
            name='staffId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_staffs.hospitalstaffprofile'),
        ),
        migrations.AlterField(
            model_name='labstaffprofile',
            name='testResult',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labstaffprofile',
            name='testType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
