# Generated by Django 4.0.1 on 2022-03-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_staffs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='address',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='hospitalstaffprofile',
            table='staff',
        ),
    ]
