# Generated by Django 4.0.1 on 2022-02-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_hospital_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_insurance_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_lab_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('hospital_staff', 'Hospital Staff'), ('doctor', 'Doctor'), ('insurance_staff', 'Insurance Staff'), ('lab_staff', 'Lab Staff'), ('administrator', 'Administrator')], default='patient', max_length=20),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
