# Generated by Django 4.0.1 on 2022-03-10 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_initial'),
        ('hospital_staffs', '0003_hospitalstaffprofile_address_and_more'),
        ('insurance_staffs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='insuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimAmount', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('testResult', models.TextField(null=True)),
                ('patientId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
                ('staffId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_staffs.hospitalstaffprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insuranceclaim',
            },
        ),
    ]
