# Generated by Django 4.0.1 on 2022-03-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointmentType', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-scheduled_date', '-created'],
            },
        ),
    ]
