# Generated by Django 4.0.1 on 2022-02-22 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('hospital_staff', 'Hospital Staff'), ('doctor', 'Doctor'), ('insurance_staff', 'Insurance Staff'), ('lab_staff', 'Lab Staff')], default='hospital_staff', max_length=20)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
