# Generated by Django 4.0.1 on 2022-02-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('hospital_staff', 'Hospital Staff'), ('doctor', 'Doctor'), ('insurance_staff', 'Insurance Staff'), ('lab_staff', 'Lab Staff'), ('administrators', 'Administrators')], default='hospital_staff', max_length=20),
        ),
    ]
