# Generated by Django 4.0.1 on 2022-03-18 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('lab_staffs', '0001_initial'),
        ('patients', '0001_initial'),
        ('hospital_staffs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.medicalinsurance')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, null=True)),
                ('transactionAmount', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('patientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
                ('staffId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_staffs.hospitalstaffprofile')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='PatientRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(null=True)),
                ('prescription', models.TextField(null=True)),
                ('doctorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_staffs.hospitalstaffprofile')),
                ('labTestId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab_staffs.labstaffprofile')),
                ('patientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
            ],
            options={
                'db_table': 'patientrecords',
            },
        ),
    ]
