# Generated by Django 4.0.1 on 2022-03-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientprofile',
            table='patient',
        ),
    ]
