# Generated by Django 4.0.1 on 2022-03-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_staffs', '0003_labstaffprofile_patientid_labstaffprofile_staffid_and_more'),
        ('hospital_staffs', '0003_hospitalstaffprofile_address_and_more'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='personalInfo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='patientprofile',
            table='patient',
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, null=True)),
                ('transactionAmount', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('patientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
                ('staffId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_staffs.hospitalstaffprofile')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='PatientRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(null=True)),
                ('prescription', models.TextField(null=True)),
                ('doctorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_staffs.hospitalstaffprofile')),
                ('labTestId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab_staffs.labstaffprofile')),
                ('patientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
            ],
            options={
                'db_table': 'patientrecords',
            },
        ),
    ]
