# Generated by Django 4.0.1 on 2022-03-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_address_patientprofile_insurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='personalInfo',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='username',
        ),
    ]
