# Generated by Django 4.0.1 on 2022-03-17 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_staffs', '0002_initial'),
        ('patients', '0003_alter_patientprofile_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientrecords',
            unique_together={('patientID', 'doctorId')},
        ),
    ]
