# Generated by Django 4.0.1 on 2022-03-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientprofile',
            table=None,
        ),
    ]
