# Generated by Django 4.0.1 on 2022-03-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patientrecords_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transactionAmount',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
