# Generated by Django 4.0.1 on 2022-03-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patientprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
