# Generated by Django 4.0.1 on 2022-03-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientprofile_address_patientprofile_insurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='insurance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='patientprofile',
            table='patient',
        ),
    ]
