<<<<<<< Updated upstream
<<<<<<< Updated upstream
# Generated by Django 4.0.1 on 2022-02-25 03:36
=======
# Generated by Django 4.0.1 on 2022-03-11 20:40
>>>>>>> Stashed changes
=======
# Generated by Django 4.0.1 on 2022-03-11 22:21
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
