# Generated by Django 4.0.1 on 2022-03-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSlot', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'doctoravailability',
            },
        ),
    ]
